### ISSUE TITLE
Relay does not properly strip color codes

### ISSUE THREAD

**Issue by spotlightishere** [LibertyLand/MessageRelayer#3]
As shown with a kit-obtained sword, this does not always strip colors to Discord's lack-of-color formatting.

":skull: `user` was slain by `other_user` using [§5LibertySword]"

This is production urgent and introduces at least 172 CVEs, obviously.

**Comment by malmeloo** [comment]
nice

**Comment by spotlightishere** [comment]
[redacted]

**Comment by Artuto** [comment]
It just that i havent updated the jar in the server lol.
